using System.Collections.Generic;

namespace ConsoleApplication1
{
    public static class MateCardTips
    {
        public static MateCardTip[] SimpleTips = new MateCardTip[]
        {
            new MateCardTip() { Header = "Attacking f7/f2", Body = @"A tactic or threat that involves targeting of the opponent's ""weakest square."" Often f7 and f2 are referred to as the weakest squares on a chessboard because they are protected only by the King at the start, so often these tactics would occur somewhere in the Opening to early Middlegame stages. There are many possible attacking ideas and threats that take place surrounding those two critical points."},
            new MateCardTip() { Header = "Attacking Castled King", Body = @"All tactics that involve attacking a castled King. These would be ideas such as sacrifices to the surrounding pawns of a castled position, pawn storms, as well as many other possible tactical themes  -- with the specific distinction that the pattern was used to attack a castled King's position, either kingside or queenside."},
            new MateCardTip() { Header = "Back Rank", Body = @"A back-rank mate is when either the Rook or Queen is attacking the enemy King, and this enemy King is trapped ""on the back rank"" (which means either the 1st or 8th rank) by his own army."},
            new MateCardTip() { Header = "Basic Checkmates", Body = @"Any type of basic checkmating ""pattern"". This definition does not apply to any position that happens to be checkmate in one or two moves, but rather, tactics that either use or climax in a basic checkmating pattern such as: King and Queen vs King; King and Rook vs King; two Rooks vs King; and two Bishops vs King."},
            new MateCardTip() { Header = "Clearance Sacrifice", Body = @"Clearance Sacrifice"" (or just ""clearance"") is a term used to describe a deliberate sacrifice of material with the goal of ""clearing"" of either a square, diagonal, or file.The most common clearance sacrifices open a critical diagonal(see example). The sacrifice of a pawn to open a square for a Knight(like a pawn moving to e5 from e4, sacrificing itself in order to free the e4-square for a Knight) would also be considered a ""positional"" clearance sacrifice."},
            new MateCardTip() { Header = "Decoy / Deflection", Body = @"A decoy is a distraction. Often a player might use a decoy to force the opponent to think about something else, while the player is actually focused on a different target entirely.Deflection is a tactic which distracts an opponent's piece from doing its job, such as defending an important square, pinning a piece or blocking an open file or diagonal. Many decoy/deflection tactics involve a sacrifice or a forcing move of some kind, thus forcing the opponent to cooperate with the decoy/deflection tactic. They are similar in their goal, which is why we have classified them as one theme. Here is an example of each type of decoy/deflection:"},
            new MateCardTip() { Header = "Defense", Body = @"To play defense, or to defend against an opponent's threat. One might ""defend"" a pawn with a piece, or you might ""play defensive moves on the kingside"" in order to stop your opponent's threats of a mating attack. By moving your pieces into position to guard and protect either a piece, a square, or a coming threat from your opponent - you are defending.We use this term for all tactics of a ""prophylactic"" or defensive nature.Often puzzles where the goal is to draw, and a defensive combination must be found in order to accomplish this, would be tagged under this category."},
            new MateCardTip() { Header = "Desperado", Body = @"A desperado tactic can sometimes be considered a sacrifice, depending on the position. The move captures an enemy piece when either one or more of your own pieces is already hanging (undefended). When material is going to be lost regardless, these situations present a rare opportunity to be ""reckless"" and take out an enemy piece along the way.This tactic often happens when both white and black have pieces under attack. A desperado can also be considered a type of Zwischenzug tactic (see ""Zwischenzug"" below)."},
            new MateCardTip() { Header = "Discovered Attack/Check", Body = @"An attack which happens when one piece moves out of the way, opening a line for another attacking piece to threaten something(either checkmate or material). A discovered check is the same thing, but the revealed piece is attacking the enemy King, so it is also check.When the piece that moves to reveal the hidden attacker also attacks a piece, this may be referred to as a discovered ""double"" attack/check."},
            new MateCardTip() { Header = "Double Check", Body = @"Checking the enemy King with two different pieces on the same move is powerful play! Unable to block or capture both threats at once, the King must always move to safety."},
            new MateCardTip() { Header = "En Passant", Body = @"The en passant capture is a special pawn attack in which the attacker may take an adjacent enemy pawn that has just jumped forward two squares."},
            new MateCardTip() { Header = "Endgame Tactic", Body = @"Any tactic that occurs in the endgame. The endgame is the last part of the game, and is generally believed to start when most of the pieces have been traded, especially after the Queens are traded."},
            new MateCardTip() { Header = "Exchange Sacrifice", Body = @"A small sacrifice of material (see ""sacrifice"") to achieve something greater.The term ""exchange sacrifice"" specifically refers to the sacrifice of a Rook for a minor piece (either Knight or Bishop) and is usually only one necessary step along the way of a forcing sequence of moves."},
            new MateCardTip() { Header = "Fork / Double Attack", Body = @"A double attack is an attack or threat on two things at once.The advantage of a double attack is that it is hard to defend two things with one move. We use the term fork to describe a double attack by a single unit, usually a Knight, Queen or pawn."},
            new MateCardTip() { Header = "Hanging Piece", Body = @"""Hanging"" is another way of saying ""undefended"" or ""loose"" in chess.A tactic that involves simply taking or exposing undefended pieces in some way would qualify.  Under this theme, one might also consider a forcing combination that climaxes with a double attack, with one or more of the targets being undefended."},
            new MateCardTip() { Header = "Interference", Body = @"To move a piece between two other attacking pieces when at least one of those attacking pieces is an opponent's piece. Sometimes a piece will interfere with two attacking pieces, thus creating confusion and often overloading (see ""overloading"") those pieces."},
            new MateCardTip() { Header = "Mate in X", Body = @"Any puzzle/position that ends with checkmate in X moves."},
            new MateCardTip() { Header = "Mating Net", Body = @"A position where the King is trapped & will soon be checkmated. The area of the board where the King is tied down is often like a ""net"" closing tighter & tighter.A player might create a mating net by cutting off all escapes for the enemy king, often by relatively quiet, non-checking moves -- but once the net is created, a forcing sequence of moves will lead to checkmate inevitably. "},
            new MateCardTip() { Header = "Overloading", Body = @"A piece that has too many things to do is ""overloaded."" For example, a bishop which has to both stop a passed pawn from Queening and guard against a checkmate is overloaded.By carrying out one threat (for example, queening the pawn) the opponent could force the overworked bishop to leave its post, allowing the checkmate threat to succeed."},
            new MateCardTip() { Header = "Pawn Promotion", Body = @"A tactic that involves promoting a pawn. Often this involves other tactics along the way, all of them being single parts of an overall goal to promote the pawn. That pawn would usually deliver decisive results. (See also ""underpromotion"")."},
            new MateCardTip() { Header = "Perpetual Check", Body = @"A situation where one player can check the opponent's King forever, but cannot checkmate it. Perpetual check is a type of drawn position. When perpetual check happens, the players usually either agree to a draw or the same position is repeated three times, resulting in a draw by the rule of ""Threefold Repetition""."},
            new MateCardTip() { Header = "Pin", Body = @"When a piece cannot move because it is blocking/guarding a more valuable piece behind it from being captured, that piece is ""pinned"". A pinning piece is a long-range piece(a Rook, Queen, or Bishop) which is aimed at one of the opponent's valuable pieces, with a less valuable opponent's piece in the way or blocking the Rook, Queen or Bishop from attacking the more valuable piece.An absolute pin is when a piece is pinned to the King, thus making it absolutely illegal to move the pinned piece."},
            new MateCardTip() { Header = "Queen Sacrifice", Body = @"A sacrifice (see ""sacrifice"") of the Queen with the distinct purpose of achieving something more valuable.Most often, a Queen Sacrifice is just one part (a single move among others) of an attempt to checkmate the enemy King or eventually win back material at the end of the combination."},
            new MateCardTip() { Header = "Removal of the Defender", Body = @"A tactic that involves eliminating the critical defensive piece that otherwise stands in the way of achieving a much greater goal(most often checkmate or the winning of large amounts of material). A player looks to remove the defender as a destructive means to achieve their goal."},
            new MateCardTip() { Header = "Sacrifice", Body = @"The act of giving up material(either making a trade that loses points or simply losing a piece or pawn for nothing) with the goal of getting something else in return. For example, a player may sacrifice the Queen in order to open up a square for a Knight where it can then checkmate the opponent.A player may also make more strategic sacrifices, such as sacrificing a pawn to gain time to develop, or sacrificing a piece to destroy the opponent's King's pawn cover."},
            new MateCardTip() { Header = "Simplification", Body = @"A simplification tactic is a forcing sequence of moves that converts an advantage into a more easily winning position.A player tries to simplify a winning position as an act of good technique, which is the skill of converting an advantage into a victory."},
            new MateCardTip() { Header = "Skewer", Body = @"A move which threatens a valuable piece(such as the King or Queen), forcing that piece to move away and allowing the attacking piece to take a less valuable piece behind the valuable one.A skewer is the opposite of a pin in many ways, since in the skewer the more valuable piece is in front. (See ""pin""). "},
            new MateCardTip() { Header = "Smothered Mate", Body = @"A checkmate by a Knight against an enemy King which has no way out because all of its escape squares are blocked by its own pieces.The King's own pieces keep it from moving, while the enemy knight puts it in check. A Smothered Mate can only occur when a King is immediately surrounded by its own pieces, with no enemy piece directly touching it by occupying a nearby square; this is why only the Knight can give Smothered Mate."},
            new MateCardTip() { Header = "Stalemate", Body = @"When a player whose turn it is has no legal moves by any of his/her pieces, but is not in check.A stalemate is a draw. A stalemate tactic would occur when the objective/goal of the puzzle was to force a stalemate from an otherwise lost or unfavorable position."},
            new MateCardTip() { Header = "Support Mate", Body = @"A support mate is a basic checkmate that occurs simply when a Queen directly assaults a King to deliver checkmate, and finds itself receiving support (protection) from one other piece.This ""supporting"" piece can be a pawn, Knight, Bishop or King."},
            new MateCardTip() { Header = "Trapped Piece", Body = @"A piece that finds itself with either no moves at all, or at least no moves that avoid the loss of material.Often, a piece might be trapped at the end of a forced sequence of moves."},
            new MateCardTip() { Header = "Underpromotion", Body = @"Promoting a pawn to a piece less than a Queen(in other words, promoting a pawn to a Knight, Rook, or Bishop). Since the Queen is the strongest piece, players almost always choose to promote their pawns to Queens.An underpromotion tactic occurs when there are special reasons that a player needs a weaker piece rather than a Queen (almost always a Knight, since it is the only piece whose move is not already reflected by the Queen's abilities) - whether to stop an opponent's threat or achieve something even better than what a Queen could offer."},
            new MateCardTip() { Header = "Vulnerable King", Body = @"A position/puzzle where tactics are arise from the exposed position of the enemy King.A ""vulnerable"" King's position may often lead to that King being put in a ""mating net"" of some kind."},
            new MateCardTip() { Header = "Windmill", Body = @"A rare tactic in which a repeated discovered check (see ""discovered attack/check"") allows one piece to go on a rampage, capturing multiple enemy pieces."},
            new MateCardTip() { Header = "X-Ray Attack", Body = @"An x-ray tactic in chess occurs when one of your long-range pieces(a Rook, Bishop, or Queen) attacks ""through"" one of your opponent's pieces to indirectly attack/threaten or defend beyond it. An x-ray tactic often occurs along with the theme of back rank mate. "},
            new MateCardTip() { Header = "Zugzwang", Body = @"A German word that literally translates to ""move compulsion."" This is a situation where every move a player could make causes him/her to lose the game(or at least significantly worsen the position)."},
            new MateCardTip() { Header = "Zwischenzug", Body = @"A German word meaning ""in-between move"". An often unexpected move inserted in between an otherwise forcing sequence of moves.The zwischenzug generally changes the result of the sequence.A ""desperado"" is a powerful example of a zwischenzug tactic."},
        };

        private static int SimpleTipCounter = 0;

        public static MateCardTip NextSimpleTip()
        {
            SimpleTipCounter = (SimpleTipCounter + 1) % SimpleTips.Length;
            return SimpleTips[SimpleTipCounter];
        }
    }

    public class MateCardTip
    {
        public string Header { get; set; }
        public string Body { get; set; }
    }
}


